version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "comida_password"
      MYSQL_DATABASE: comidamqtt
      MYSQL_USER: comida
      MYSQL_PASSWORD: "password"
      TZ: America/Mexico_City
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - redcomida

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9002:9002"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - redcomida

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mysql
      - mqtt
    working_dir: /app
    command: ["./espera-mysql.sh", "node", "server.js"]
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    networks:
      - redcomida
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=comida
      - DB_PASSWORD=password
      - DB_NAME=comidamqtt

  cocina:
    build:
      context: ./cocina
    container_name: cocina
    depends_on:
      - backend
    ports:
      - "5174:4173"  # puerto externo 5174 → puerto interno Vite 4173
    networks:
      - redcomida

  comensal:
    build:
      context: ./comensal
    container_name: comensal
    depends_on:
      - backend
    ports:
      - "5173:4173"  # puerto externo 5173 → puerto interno Vite 4173
    networks:
      - redcomida

networks:
  redcomida:
    driver: bridge
