CREATE DATABASE IF NOT EXISTS comidamqtt;

USE comidamqtt;

CREATE TABLE IF NOT EXISTS pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productos JSON NOT NULL,
  estado VARCHAR(50) DEFAULT 'Recibido',
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
